spring:
  application:
    name: eureka-server
server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    com.netflix: DEBUG