spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-application?currentSchema=payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

axon:
  eventhandling:
    processors:
      payment-group:
        mode: subscribing
  serializer:
    events: jackson
    general: jackson
    messages: jackson

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}